"""Altera nome Foreign Key Contas

Revision ID: 32991dc21937
Revises: 910374970530
Create Date: 2025-05-22 15:40:58.475851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32991dc21937'
down_revision: Union[str, None] = '910374970530'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_a_pagar_e_receber', sa.Column('fornecedor_cliente_id', sa.Integer(), nullable=True))
    op.drop_constraint('contas_a_pagar_e_receber_fornecedor_id_fkey', 'contas_a_pagar_e_receber', type_='foreignkey')
    op.create_foreign_key(None, 'contas_a_pagar_e_receber', 'fornecedor_cliente', ['fornecedor_cliente_id'], ['id'])
    op.drop_column('contas_a_pagar_e_receber', 'fornecedor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_a_pagar_e_receber', sa.Column('fornecedor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contas_a_pagar_e_receber', type_='foreignkey')
    op.create_foreign_key('contas_a_pagar_e_receber_fornecedor_id_fkey', 'contas_a_pagar_e_receber', 'fornecedor_cliente', ['fornecedor_id'], ['id'])
    op.drop_column('contas_a_pagar_e_receber', 'fornecedor_cliente_id')
    # ### end Alembic commands ###
