"""Cria tabela de Fornecedor Cliente

Revision ID: 43e1e0739ae1
Revises: 47e35f46a2a1
Create Date: 2025-05-22 13:41:24.520467

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43e1e0739ae1'
down_revision: Union[str, None] = '47e35f46a2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor_cliente',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('nome', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('contas_a_pagar_e_receber', 'descricao',
                    existing_type=sa.VARCHAR(length=30),
                    type_=sa.String(length=255),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contas_a_pagar_e_receber', 'descricao',
                    existing_type=sa.String(length=255),
                    type_=sa.VARCHAR(length=30),
                    existing_nullable=True)
    op.drop_table('fornecedor_cliente')
    # ### end Alembic commands ###
