"""Acrescenta Data Previsao para controlar limite de contas criadas

Revision ID: ac9a9038e946
Revises: b2cfc7b3717c
Create Date: 2025-05-23 10:51:23.334025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9a9038e946'
down_revision: Union[str, None] = 'b2cfc7b3717c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_a_pagar_e_receber', sa.Column('data_previsao', sa.DateTime(), nullable=True))
    op.execute("update contas_a_pagar_e_receber set data_previsao = now()")
    op.alter_column('contas_a_pagar_e_receber', 'data_previsao', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contas_a_pagar_e_receber', 'data_previsao')
    # ### end Alembic commands ###
