"""Acrescenta Data Baixa, Valor Baixa e Está Baixada no modelo Contas a Pagar e Receber

Revision ID: b2cfc7b3717c
Revises: 32991dc21937
Create Date: 2025-05-23 08:43:43.827185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2cfc7b3717c'
down_revision: Union[str, None] = '32991dc21937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_a_pagar_e_receber', sa.Column('data_baixa', sa.DateTime(), nullable=True))
    op.add_column('contas_a_pagar_e_receber', sa.Column('valor_baixada', sa.Numeric(), nullable=True))
    op.add_column('contas_a_pagar_e_receber', sa.Column('esta_baixada', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contas_a_pagar_e_receber', 'esta_baixada')
    op.drop_column('contas_a_pagar_e_receber', 'valor_baixada')
    op.drop_column('contas_a_pagar_e_receber', 'data_baixa')
    # ### end Alembic commands ###
